# Generated by Django 3.2.16 on 2022-10-31 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persona',
            fields=[
                ('ci', models.CharField(help_text='entre el carnet de identidad', max_length=11, primary_key=True, serialize=False)),
                ('name', models.CharField(help_text='Ingrese el nombre del género (p. ej. Ciencia Ficción, Poesía Francesa etc.)', max_length=200)),
                ('last_name', models.CharField(help_text='Ingrese el apellido (p. ej. Ciencia Ficción, Poesía Francesa etc.)', max_length=200)),
            ],
        ),
    ]
